CONFIG_NAME: customdevnet
PRESET_BASE: mainnet

# Genesis
GENESIS_FORK_VERSION: 0x90000000

# Altair
ALTAIR_FORK_EPOCH: 1
ALTAIR_FORK_VERSION: 0x90000001

# Merge
BELLATRIX_FORK_EPOCH: 2
BELLATRIX_FORK_VERSION: 0x90000002

TERMINAL_TOTAL_DIFFICULTY: 1

# Capella
CAPELLA_FORK_EPOCH: 3
CAPELLA_FORK_VERSION: 0x90000003
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Deneb
DENEB_FORK_VERSION: 0x90000004
DENEB_FORK_EPOCH: 4

FULU_FORK_EPOCH: 18446744073709551615  # FAR_FUTURE_EPOCH
FULU_FORK_VERSION: 0x90000005


ELECTRA_FORK_VERSION: 0x90000005

DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Time parameters
SECONDS_PER_SLOT: 2
SLOTS_PER_EPOCH: 32

TERMINAL_BLOCK_HASH: 0x636afad9580c30b987c5e24522d7349685ea7502e8efdf5ed838e2379bf82b93
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0